spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plusplus
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

jwt:
  secret:
    key:
      6re466CH7KeA7Jet7Iuc67CU66Gc6rCR64uI64uk662Q7KOgP+yYiD/slYTslYTri4g=

logging:
  level:
    root: info
    com:
      example: debug
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace